### ISSUE TITLE
这个自定义的maven依赖在哪里下载?

### ISSUE THREAD

**Issue by koen100** [smilewangsy/wangsy-january#3]
<dependency>
            <artifactId>smile-common</artifactId>
            <groupId>wang.smile.common</groupId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

**Comment by tigpan** [comment]
同求：有知道的加qq1968939697交流

**Comment by koen100** [comment]
> 同求：有知道的加qq1968939697交流

https://github.com/hellosmile01/wang-smile-common
